spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/lol?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: wuzijiao
     driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml